== digital signatures
[%hardbreaks]

_Public key cryptograhy_ is widely used to build _digital signatures_, simple protocol: _signature_ = encrypted data hash with _secret key_ (signature = encrypt( hash(data), _secret key_ )), verification is a decryption of _signature_ by _public key_ and comparison of hashes (hash(data) == decrypt( signature, _public key_ )).

image::images/digital-signatures-2.svg[float="left",align="center"]


Any _digital signatures_ protocol should implement two methods _sign_ and _verify_, _sign_ produces _signature_ a unique bitstring, _verify_ takes _signature_ and _public key_ to verify correctness and authenticity.

=== multisig
It's construction when multiple keys (parties) are used to _sign_ data that usually required in distributed protocols.

=== ring signatures
It's used for privacy preserving. Signature can be produced by any member of a group without revealing who exactly. Verifier can only verify that signature is correct and one of the group memders created this signature.

=== one time signatures
The idea is simple to use pair (_secret_,_public_) key to sign message/data only once.

To construct _one time signatures_ many _secret keys_ are generated and _public keys_ _merkle tree_ are built for verification, each _secret key_ is used only once. Any well known algorithm to _sign_ and _verify_ can be used + _merkle tree_ for test. This is a bit over redundant but almost impossible to fake your signature. It's scalable by generating new array of _secret keys_ and _merkel tree_ linked to previous one.

image::images/one-time-signatures.svg[float="left",align="center"]


_Lamport signature_ and other methods are exist to construct _one time_ _digital signatures_. Any custom _protocol_ can be build for specific needs.

image::images/lamport-signatures.svg[float="left",align="center"]

There are some standards: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-208-draft.pdf[hash-based signature schemes], https://tools.ietf.org/html/rfc8391[xmss]

=== aggregation signatures
For distributed protocols multiple signatures of one data block are used very often, some aggregation signature schemes were designed (for instance BLS) to decrease metadata size, short signature authenticates all participants, but security concerns are there.




