== distributed consensus protocols
It's simply consensus on _state transition_ in distributed network without trust among participants and users (transactions senders). State transition is processed by ordered list of _transactions_, _transactions_ can be grouped by blocks (for traffic optimisation).

Technically to achieve consensus on _state transition_ each node should send _digitally signed_ messages with some information of _state transition_ to other nodes. To reduce number of messages one coordinator (_block producer_) node is selected each time (by some algorithm).

=== byzantine fault tolerance (BFT)
Tolerance to malicious minority of participants, formalized as byzantine generals problem.

=== proof of work (POW)
It's a _block producer_ selection mechanism. Proof of that computationally hard problem is solved (_POW_) is used to select a _block producer_ node who provides state transition for one block, for another block - another block producer is selected.

=== proof of stake (POS)
Same as _POW_ but different selection mechanism among nodes with staked balance is used, bigger stake - bigger chanses to be selected.

If internal economy exists block producers are incentivized by reward.

=== scalability trilemma
A term coined by Vitalik Buterin for 3 things: _scalability_, _security_, _decentralization_ you can't achive all three at the same time.

