[role="pagenumrestart"]
[[intro_chapter]]
== intro
[%hardbreaks]

_New/old_ *technologies* for the _new/old_ web:

=== hash function
It's widely used for data verification and indexing in data storage and crypto protocols.

=== hash table
It's used as a quick data index, _O(1)_ overage search time (if no collisions).

=== merkle tree (hash tree)
For data blocks (parts of a big one) verification and for proofs in p2p protocols.

=== distributed hash table (DHT)
It's used for nodes search in distributed network.

=== symmetric encryption
For data encryption and decryption by one key.

=== asymmetric encryption
For data encryption by one key and decryption by another key, this key pair are linked.

=== digital signature
It's  widely used for data authenticity and verification.

=== blockchain
It's growing data (chain of blocks) consistency verification _data structure_ and _mechanism_.

=== direct acyclic graph (DAG)
Same as _blockchain_ but instead of chain of blocks direct acyclic graph is used.

=== distributed consensus protocol
It's a protocol to reach consensus of some state in distributed network of nodes without _trust_.

=== zero knowledge proof
One party (prover) proves to another party (verifier) a knowledge of _x_ without revealing _x_ (zero knowledge of _x_), only _proof_ of _something_ with no other information about that _something_.

=== smart contract
It's a technology for digital contract's execution in _trustless_ environment, _smart_contract_ in simple case can be processed between two parties, or executed for many parties on top of distributed ledger (blockchain) network

=== L1 protocols
L1 is an alias for distributed ledger protocols or similar.

=== L2 protocols
L2 is an alias for protocols on top of L1 protocols.

=== Byzantine fault tolerance (BFT)
It's a tolerance of distributed network (protocol) to attacks from malicious participants.

=== Payment channel
It's a p2p protocol for instant payments in any crypto, token or asset.

=== State channel
Same as payment channel but for any state.

=== Lightning network
It's an L2 network (protocol) of payment/state channels.

=== distributed application (dapp)
It's an app runs on top of distributed protocol (L1/L2).

=== tokenomic
It's a digital economy system with custom rules of tokens _emission_, _transfers_, _exchange_, etc., tokens can be _minted_ (_generated_) independently or linked to fiat money or other kind of assets.

=== cryptocurrency
It's a digital currency, usually implemented on top of _distributed ledger_ (_blockchain_) network.

=== stablecoin
Low volatility (stable) digital coin linked somehow to stable asset (fiat money, metal, etc. ).

=== defi
Decentralized finance, decentralized financial applications. It's a _dapp_ that can provide financial services alternatively to traditional financial systems.

=== fintech
Financial technologies applications and services. It's an _app_ that can replace whole bank.


